/**
 * Production build generator for SaiU Timetable.
 *
 * Every deploy must produce a unique BUILD_ID. This script:
 *
 *   1. Computes the next BUILD_ID (YYYY-MM-DD-NNN) from .buildinfo.
 *   2. Writes the version into js/generated/build.js and build.json.
 *   3. Appends `?v=BUILD_ID` to every static asset reference in
 *      index.html, manifest.json, and to every relative module import
 *      in js/**\/*.js. Versioned URLs are never served stale by a cache.
 *   4. Injects BUILD_ID into sw.js (the `__BUILD_ID__` marker), which
 *      also changes the file's bytes so browsers always detect a
 *      Service Worker update after a deploy.
 *
 * Run with: node scripts/build.mjs
 * Commit the output, then push to deploy.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const BUILDINFO = join(ROOT, '.buildinfo');

const pad = (n) => String(n).padStart(2, '0');
const padSeq = (n) => String(n).padStart(3, '0');

function todayStamp() {
  const d = new Date();
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

function nextBuildId() {
  const today = todayStamp();
  let last = null;
  if (existsSync(BUILDINFO)) {
    try { last = JSON.parse(readFileSync(BUILDINFO, 'utf8')); } catch { last = null; }
  }
  const seq = last && last.id && last.id.startsWith(today) ? Number(last.id.slice(-3)) + 1 : 1;
  return `${today}-${padSeq(seq)}`;
}

const BUILD_ID = nextBuildId();
console.log(`[build] BUILD_ID = ${BUILD_ID}`);

const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const write = (p, content) => writeFileSync(join(ROOT, p), content);

// ---------------------------------------------------------------------------
// sw.js — inject the build id. Replacing the value changes the file's bytes
// every build, guaranteeing the browser notices a Service Worker update.
// ---------------------------------------------------------------------------
{
  const file = 'sw.js';
  const src = read(file);
  if (!/const BUILD_ID = '([^']*)'/.test(src)) {
    console.error(`[build] ${file} is missing the "const BUILD_ID" assignment`);
    process.exit(1);
  }
  write(file, src.replace(/const BUILD_ID = '([^']*)'/, `const BUILD_ID = '${BUILD_ID}'`));
}

// ---------------------------------------------------------------------------
// js/generated/build.js — build info exposed to the application.
// ---------------------------------------------------------------------------
write('js/generated/build.js', `// Generated by build.mjs - do not edit by hand.\nwindow.__TT_BUILD_ID__ = '${BUILD_ID}';\n`);

// ---------------------------------------------------------------------------
// build.json — machine-readable build id for the startup version check.
// ---------------------------------------------------------------------------
write('build.json', `${JSON.stringify({ id: BUILD_ID }, null, 2)}\n`);

// ---------------------------------------------------------------------------
// index.html — version every same-origin static asset reference.
// ---------------------------------------------------------------------------
function versionRefs(html, patterns) {
  for (const pat of patterns) {
    html = html.replace(new RegExp(`(${pat})(\\?v=[^"']*)?`, 'g'), `$1?v=${BUILD_ID}`);
  }
  return html;
}

{
  const file = 'index.html';
  let html = read(file);

  // Ensure js/generated/build.js is loaded before app.js (sets window.__TT_BUILD_ID__).
  if (!/<script src="js\/generated\/build\.js/.test(html)) {
    html = html.replace(
      '<link rel="stylesheet" href="',
      '<script src="js/generated/build.js?v=' + BUILD_ID + '"></script>\n    <link rel="stylesheet" href="'
    );
  }

  html = versionRefs(html, [
    'style\\.css',
    'manifest\\.json',
    'icons/[A-Za-z0-9._/-]+\\.png',
    'js/core/app\\.js',
    'js/generated/build\\.js',
  ]);
  write(file, html);
}

// ---------------------------------------------------------------------------
// game.html / 404.html — version every same-origin static asset reference.
// These pages are not otherwise processed by the build, but they must still
// point at the current BUILD_ID so a cache never serves them stale CSS/JS.
// ---------------------------------------------------------------------------
for (const file of ['game.html', '404.html']) {
  if (!existsSync(join(ROOT, file))) continue;
  write(file, versionRefs(read(file), [
    'style\\.css',
    'js/services/timetable-sync\\.js',
    'js/game/breakout\\.js',
    'icons/[A-Za-z0-9._/-]+\\.png',
  ]));
}

// ---------------------------------------------------------------------------
// js/**\/*.js — version every relative module import (`from './x.js'` /
// `import './x.js'`). Only import/export specifiers are rewritten, so
// other strings containing `./foo.js?v=...` (e.g. the SW registration
// URL in app.js) are left untouched. The generated build.js is skipped.
// ---------------------------------------------------------------------------
{
  function walk(dir) {
    for (const entry of readdirSync(join(ROOT, dir), { withFileTypes: true })) {
      const file = join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(file);
      } else if (entry.name.endsWith('.js') && entry.name !== 'build.js') {
        let src = read(file);
        src = src.replace(
          /(\bfrom\s+|\bimport\s+)(['"])(\.{1,2}\/[^'"?#]+\.js)(\?v=[^'"]*)?\2/g,
          `$1$2$3?v=${BUILD_ID}$2`
        );
        write(file, src);
      }
    }
  }
  walk('js');
}

// ---------------------------------------------------------------------------
// manifest.json / manifest-light.json — version icon srcs.
// ---------------------------------------------------------------------------
for (const file of ['manifest.json', 'manifest-light.json']) {
  const manifest = JSON.parse(read(file));
  if (manifest.icons) {
    for (const icon of manifest.icons) {
      icon.src = icon.src.split('?')[0] + `?v=${BUILD_ID}`;
    }
  }
  write(file, `${JSON.stringify(manifest, null, 2)}\n`);
}

// ---------------------------------------------------------------------------
// .buildinfo — persist the generated id for the next run.
// ---------------------------------------------------------------------------
write('.buildinfo', `${JSON.stringify({ id: BUILD_ID }, null, 2)}\n`);

console.log(`[build] done — ${BUILD_ID}`);
