/**
 * Minify JS and CSS files for production.
 *
 * Uses terser for JS (with --module for ES module support) and a simple
 * CSS minifier. Preserves all functional code — no tree-shaking, no dead
 * code elimination, no renaming of exports.
 *
 * Run: node scripts/minify.mjs
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, extname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');

// ---------------------------------------------------------------------------
// Simple CSS minifier: strip comments, collapse whitespace, remove newlines.
// Safe — preserves all selectors, properties and values.
// ---------------------------------------------------------------------------
function minifyCSS(css) {
    return css
        // strip multi-line comments
        .replace(/\/\*[\s\S]*?\*\//g, '')
        // collapse whitespace
        .replace(/\s+/g, ' ')
        // remove spaces around special chars
        .replace(/\s*([{}:;,>~+])\s*/g, '$1')
        // remove trailing semicolons before }
        .replace(/;}/g, '}')
        // trim
        .trim();
}

// ---------------------------------------------------------------------------
// JS minification via terser (dynamic import so the script works even if
// terser is not installed — falls back to no minification).
// ---------------------------------------------------------------------------
let terser;
try {
    terser = await import('terser');
} catch {
    console.warn('[minify] terser not installed — skipping JS minification');
}

async function minifyJS(code, filePath) {
    if (!terser) return code;
    const result = await terser.minify(code, {
        compress: {
            // Safe defaults — no dead-code removal or pure-function opts
            passes: 1,
            toplevel: false,
            // Keep all exports/imports intact
            module: true,
        },
        mangle: {
            // Don't rename top-level or exported identifiers
            toplevel: false,
            // Keep property names (some are accessed dynamically)
            properties: false,
        },
        format: {
            comments: false,
            // Keep ES module syntax
            ecma: 2020,
        },
        // ES module support
        module: true,
        sourceMap: false,
        // Don't rename to avoid breaking dynamic property access
        keep_fnames: true,
    });
    return result.code || code;
}

// ---------------------------------------------------------------------------
// Walk JS directory and minify all .js files (skip build.js which is
// regenerated by build.mjs, and skip *.min.js).
// ---------------------------------------------------------------------------
async function minifyJsDir(dir) {
    let totalBefore = 0;
    let totalAfter = 0;
    const files = [];

    function walk(d) {
        for (const entry of readdirSync(d, { withFileTypes: true })) {
            const fp = join(d, entry.name);
            if (entry.isDirectory()) {
                walk(fp);
            } else if (entry.name.endsWith('.js') && !entry.name.endsWith('.min.js') && entry.name !== 'build.js' && entry.name !== 'serve.mjs' && entry.name !== 'minify.mjs' && entry.name !== 'build.mjs') {
                files.push(fp);
            }
        }
    }
    walk(dir);

    for (const fp of files) {
        const src = readFileSync(fp, 'utf8');
        const minified = await minifyJS(src, fp);
        const rel = relative(dir, fp);
        const before = Buffer.byteLength(src);
        const after = Buffer.byteLength(minified);
        totalBefore += before;
        totalAfter += after;
        if (before > after) {
            writeFileSync(fp, minified);
            console.log(`  ${rel}: ${before} → ${after} bytes (${Math.round((1 - after / before) * 100)}% smaller)`);
        } else {
            console.log(`  ${rel}: already optimal (${before} bytes)`);
        }
    }
    return { totalBefore, totalAfter };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
console.log('[minify] JavaScript files...');
const { totalBefore: jsBefore, totalAfter: jsAfter } = await minifyJsDir(join(ROOT, 'js'));
console.log(`[minify] JS total: ${jsBefore} → ${jsAfter} bytes (${Math.round((1 - jsAfter / jsBefore) * 100)}% saved)\n`);

console.log('[minify] CSS...');
const cssPath = join(ROOT, 'style.css');
const cssSrc = readFileSync(cssPath, 'utf8');
const cssMin = minifyCSS(cssSrc);
writeFileSync(cssPath, cssMin);
const cssSaved = Math.round((1 - Buffer.byteLength(cssMin) / Buffer.byteLength(cssSrc)) * 100);
console.log(`[minify] style.css: ${Buffer.byteLength(cssSrc)} → ${Buffer.byteLength(cssMin)} bytes (${cssSaved}% saved)\n`);

console.log('[minify] done');
